### ISSUE TITLE
Incorrect error codes lead to Unexpected error (Code: 104)

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/woo#103]
I'm working on improvement of a Woo benchmark at 
and discovered, that sometimes Woo logs errors like this:

```
woo:  <ERROR> [08:11:41] woo.ev.tcp - Unexpected error (Code: 104)
```

I've dig into the source code and found [the place where it logs](https://github.com/fukamachi/woo/blob/181a838bc92d9fe224219bdd7e833f13159d5f95/src/ev/tcp.lisp#L117) an error:

Also, I've discovered that Woo [defines error codes](https://github.com/fukamachi/woo/blob/181a838bc92d9fe224219bdd7e833f13159d5f95/src/syscall/main.lisp#L46-L54) like this, but on Ubuntu 22.04 they are different. Here in comments I've added results of the grep in header files on my linux virtual machine:

```lisp
;; /usr/include/asm-generic/errno.h:#define        EWOULDBLOCK     EAGAIN  /* Operation would block */
(defconstant EWOULDBLOCK 35.)
;; correct
(defconstant EPIPE 32.)
;; correct
(defconstant EINTR 4.)
;; /usr/include/asm-generic/errno.h:#define        EPROTO          71      /* Protocol error */
(defconstant EPROTO 100.)
;; /usr/include/asm-generic/errno.h:#define        ECONNABORTED    103     /* Software caused connection abort */
(defconstant ECONNABORTED 53.)
;; /usr/include/asm-generic/errno.h:#define        ECONNREFUSED    111     /* Connection refused */
(defconstant ECONNREFUSED 61.)
;; /usr/include/asm-generic/errno.h:#define        ECONNRESET      104     /* Connection reset by peer */
(defconstant ECONNRESET 54.)
;; /usr/include/asm-generic/errno.h:#define        ENOTCONN        107     /* Transport endpoint is not connected */
(defconstant ENOTCONN 57.)
;; correct
(defconstant EAGAIN 11.)
```

Should these constants be fixed in Woo sources?

**Comment by fukamachi** [comment]
Thanks for the patch!
Since the error codes are possibly different in other environments like Darwin, so need to look into it.
It may be better to use Grovel to retrieve them.

**Comment by svetlyak40wt** [comment]
If you wish, I could try to redo this patch for using groveler.

**Comment by fukamachi** [comment]
Oh, it'd be great if you don't mind. Thanks!

**Comment by svetlyak40wt** [comment]
Cool! Thank you! I completely forgot about this issue!

**Comment by fukamachi** [comment]
Thank you for reporting. 🙂
