### ISSUE TITLE
How to load contents from a file?

### ISSUE THREAD

**Issue by Corazone777** [fukamachi/woo#105]
Not really an issue with the woo itself, rather a lack of understanding from my part.

I want to do something like this

```
(defparameter *file-contents* (read-html-file "index.html"))

(defvar *app*
  (lambda (env)
    '(200 (:content-type "text/plain") (*file-contents*))))

(defun start-server ()
  (woo:run
   *app*))
```
I searched online and was not able to find any answers.

**Comment by fukamachi** [comment]
A pathname is allowed as a response body like:

```common-lisp
(defvar *app*
  (lambda (env)
    '(200 (:content-type "text/plain") #P"index.html")))
```

Lack's README will help you to get how to write an app.

https://github.com/fukamachi/lack

**Comment by Corazone777** [comment]
Thanks you so much
