### ISSUE TITLE
Server hangs with certain GET request

### ISSUE THREAD

**Issue by tetrazolium** [fukamachi/woo#109]
**Environment Info:**
```
Machine: Linux 5.15.0-200.131.27.el8uek.aarch64
Lisp: SBCL 2.3.10
ASDF: 3.3.1
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp-versions.txt">
; 9.50KB
==================================================
9,728 bytes in 0.00 seconds (0.00KB/sec)
Quicklisp: 2023-10-21 (latest)
NIL
```
The OS is Oracle Linux 8

**Reproduction steps:**
Run
```
(woo:run
  (lambda (env)
    (declare (ignore env))
    '(200 (:content-type "text/plain") ("Hello, World"))))
```
Then, outside of sbcl, do "ncat \<ip> \<port>", then type
`GET / #.(+ 1 1)`
This causes the server to hang. I've tested on both a server running Oracle Linux and on a x64 laptop, and this get request causes the server to hang on both, regardless of whether the request originates remotely or locally. Another get request that causes this is ```GET / #`(+ 1 1)```
**Backtrace:**
Not available, because the server hangs and nothing is output

**Comment by fukamachi** [comment]
Thank you for reporting.
It appears that fast-http is stuck in an infinite loop for an invalid HTTP version.
I'll work on fixing it.

**Comment by fukamachi** [comment]
I made changes in fast-http to fix it.
Please confirm it with the HEAD of fast-http.

**Comment by tetrazolium** [comment]
That fixed it, thank you!

**Comment by fukamachi** [comment]
It’s intended.  If it finds a character which isn’t allowed in a URL path and the HTTP version either, it will raise an error beacuse every line is supposed to end with CRLF in HTTP.

**Comment by fukamachi** [comment]
I got your point. Though, it is still intended because Woo accepts only HTTP/1.0 or HTTP/1.1 since it's an HTTP/1 server.

**Comment by tetrazolium** [comment]
Ah, I see. I mostly submitted it since I've been trying to run clack with woo on a public server, but it kept triggering the debugger from random internet traffic. I'll just try to work around it then.

**Comment by fukamachi** [comment]
You can disable the CL debugger by passing `:debug nil` to `woo:run`.
