### ISSUE TITLE
woo.response::current-rfc-1123-timestamp triggers error with SBCL 2.4.6

### ISSUE THREAD

**Issue by gibsonf1** [fukamachi/woo#113]
I've just updated to SBCL 2.4.6, and now the woo.response::current-rfc-1123-timestamp function triggers the following error:

```
Attempt to modify a read-only object at #xFFF7B8B98.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]
```

The quick workaround for now with local-time library:

```
(defun woo.response::current-rfc-1123-timestamp ()
    (local-time:format-timestring nil (local-time:now) :format +rfc-1123-format+ :timezone local-time:+gmt-zone+)
    )
```

**Comment by fukamachi** [comment]
What the commit SHA1 of Woo are you using?
It should have been fixed by #106.

**Comment by gibsonf1** [comment]
It looks we had issues getting that update and we're running old code, thanks!

**Comment by gibsonf1** [comment]
Eitaro,



Thanks for responding on this (and the great libraries!).  We just updated all libraries to latest with quicklisp but had an issue with the woo update.  Thanks!



My best,

Fred


Fred Gibson

Founder & CEO

mobile: 415.335.8232





1255 Treat Blvd, Suite 300
PMB#4611
Walnut Creek, CA  94597

















---- On Sat, 06 Jul 2024 06:13:39 -0700 Eitaro Fukamachi ***@***.***> wrote ---





What the commit SHA1 of Woo are you using?
 It should have been fixed by https://github.com/fukamachi/woo/pull/106.
