### ISSUE TITLE
HTTPS/SSL Failing on Simple App

### ISSUE THREAD

**Issue by daninus14** [fukamachi/woo#119]
Hi,

First: thanks so much for the new **https/ssl** functionality!

I was just trying to make a simple app to test the new HTTPS.

Here's the sample app

```common-lisp
(ql:quickload "clack")
(ql:quickload "woo")

(defvar *app*
  (lambda (env)
    (declare (ignore env))
    '(200 () ("Hello from MyDomain.com"))))

(defvar *clack-server*
  (clack:clackup *app*
                 :server :woo
                 :ssl T
		 :address "0.0.0.0"
                 :port 443
                 :ssl-cert-file #P"/etc/letsencrypt/live/mydomain.com/fullchain.pem"
                 :ssl-key-file #P"/etc/letsencrypt/live/mydomain.com/privkey.pem"
                 ;; :debug NIL
                 ))
```

I redacted the domain name.

I am running the app like this: `ros run -l "clackup-ssl-app.lisp"`

However, I get the following errors when visiting with chrome:

```
To load "clack":
  Load 1 ASDF system:
    clack
; Loading "clack"
..
To load "woo":
  Load 1 ASDF system:
    woo
; Loading "woo"
....
Woo server is started.
Listening on 0.0.0.0:443.
*  <ERROR> [14:09:18] woo - HTTP parse error: INVALID-METHOD: invalid HTTP method
 <ERROR> [14:09:18] woo - HTTP parse error: INVALID-METHOD: invalid HTTP method
```

Any ideas on what's going wrong? Is there anything I'm missing?

**Note:** When running a simple non ssl app on port 80, the woo server works as expected. This seems to be an issue related to the SSL. Maybe the parsing of an HTTPS is different?

**Note 2:** If I substitue `:hunchentoot` instead of `:woo` for the server, everything works as expected.

**Comment by fukamachi** [comment]
It might be wrong, as I tested only self-signed certificates.
I'll test with Let's Encrypt when I have time.

**Comment by fukamachi** [comment]
One thing I'd like to know is if you are using the latest Woo.
Check where you got it and ensure it was loaded from the expected place.

**Comment by daninus14** [comment]
After deleting the cache and a bunch of things everything works! Sorry to bother! I can confirm it works with letsEncrypt. Thanks for the help!
