### ISSUE TITLE
When I use (ql:quickload "woo"),  there is a problem on "static-vectors"

### ISSUE THREAD

**Issue by kuangdash** [fukamachi/woo#13]
```
Error while trying to load definition for system static-vectors
from pathname
d:/Fire_Workspace/emacs_24/home/clozure/quicklisp/dists/quicklisp/software/static-vectors-1.6/static-vectors.asd:

   You need ASDF >= 2.32 to load this system correctly.
   [Condition of type ASDF:LOAD-SYSTEM-DEFINITION-ERROR]
```

But anyhow, I had updated asdf.lisp by (ql:update-all-dists)

**Comment by eudoxia0** [comment]
static-vectors has this in the system definition:

```lisp
#.(unless (or #+asdf3 (asdf/driver:version<= "2.32" (asdf-version)))
    (error "You need ASDF >= 2.32 to load this system correctly."))
```

It works for me, try posting the output of `(asdf:asdf-version)`. In my case it's `"3.1.3"`.

**Comment by kuangdash** [comment]
Firstly, I updated the asdf.lisp manually, then still there is an error ;
Secondly, I checked the version of asdf.lisp by ```(asdf:asdf-version) ``` , then it's ``` "2.26" ```;
Thirdly, I meditated a little, then deleted the directory ``` "cache" ``` in the main directory of ``` quicklisp ```;
Finally, It works! 
ありがとう(●'◡'●)
