### ISSUE TITLE
Tornado is using only one IOLoop

### ISSUE THREAD

**Issue by Dith3r** [fukamachi/woo#26]
Please consider using:

        server.bind(__port__, __host__, 0, __backlog__)
        server.start(0) # this will start one process per core 
        tornado.ioloop.IOLoop.current().start()

**Comment by fukamachi** [comment]
All servers in the benchmark that Tornado is in are using only single CPU core. It may be possible to add Tornado to [multicore benchmark](https://github.com/fukamachi/woo/blob/master/images/benchmark-multicore.png) with the setting you said.

**Comment by fukamachi** [comment]
I don't have a plan to add it for now. Closing.
