### ISSUE TITLE
Does not work with ningle.

### ISSUE THREAD

**Issue by VitoVan** [fukamachi/woo#38]
<ERROR> [13:43:28] woo - fast-http error: Callback Error: the message-complete callback failed
  #<NINGLE.APP:<APP> {E51DFA9}> fell through ETYPECASE expression.
  Wanted one of (FUNCTION SYMBOL).

This ningle: http://8arrow.org/ningle/

Toot and Wookie and Hunchentoot works well.

**Comment by fukamachi** [comment]
Need more information. Show the code.

**Comment by VitoVan** [comment]
```Lisp
(ql:quickload '(clack ningle))
(defvar *app* (make-instance 'ningle:<app>))
(setf (ningle:route *app* "/")
      "Welcome to  ningle!")
(clack:clackup *app* :server :woo)
```

Then, visit http://localhost:5000/

Switch to the terminal, it shows:

> Woo server is started.
Listening on localhost:5000.
 <ERROR> [14:02:10] woo - fast-http error: Callback Error: the message-complete callback failed
  #<NINGLE.APP:<APP> {D870009}> fell through ETYPECASE expression.
  Wanted one of (FUNCTION SYMBOL).

**Comment by fukamachi** [comment]
Cannot reproduce it. Check the versions of your Quicklisp dist, Clack, Lack and ningle.

**Comment by VitoVan** [comment]
```Lisp
(quicklisp:update-client)
(quicklisp:update-all-dists)
```
After that, problem has gone.

Thank you, it's my fault.
