### ISSUE TITLE
(ql:quickload "woo") on lipspworks 7.0 failed.

### ISSUE THREAD

**Issue by hufengtao** [fukamachi/woo#49]
Error: Error while trying to load definition for system woo from pathname /home/hft/quicklisp/dists/quicklisp/software/woo-20160318-git/woo.asd:
          COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">
   1 (continue) Retry compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">.
   2 Continue, treating compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat"> as having been successful.
   3 (abort) Give up on "cffi-grovel"
   4 Try loading /home/hft/quicklisp/dists/quicklisp/software/woo-20160318-git/woo.asd again.
   5 Give up loading /home/hft/quicklisp/dists/quicklisp/software/woo-20160318-git/woo.asd.
   6 Try loading another file instead of /home/hft/quicklisp/dists/quicklisp/software/woo-20160318-git/woo.asd.
   7 Retry ASDF operation.
   8 Retry ASDF operation after resetting the configuration.
   9 Give up on "woo"
  10 Return to level 0.
  11 Return to top loop level 0.

**Comment by macdavid313** [comment]
Can't reproduce this problem... which platform you are using? And may I ask any specific reasons to use LispWorks to load WOO?

**Comment by knobo** [comment]
Do you have lispworks32 bit version on 64 bit platform?

**Comment by hufengtao** [comment]
sorry, this issue have nothing to do with woo.  the reason is that lipspworks 7.0 use asdf 3.1.4 by default which cause this issue. update asdf to >= 3.1.5 is ok.
