### ISSUE TITLE
Add woo to TechEmpower's Web Framework Benchmarks would be great

### ISSUE THREAD

**Issue by muyinliu** [fukamachi/woo#69]
[TechEmpower's Web Framework Benchmarks](https://www.techempower.com/benchmarks/) is a performance comparison of many web application frameworks executing fundamental tasks such as JSON serialization, database access, and server-side template composition. Each framework is operating in a realistic production configuration. Results are captured on Amazon EC2 and on physical hardware. The test implementations are largely community-contributed and all source is available at the [GitHub repository](https://github.com/TechEmpower/FrameworkBenchmarks).

There is no Common Lisp frameworks in the benchmarks now, so it will be great if woo become the first one :)

**Comment by knobo** [comment]
#16

**Comment by GertThiel** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/4684

**Comment by fukamachi** [comment]
Closing since it seems to be done.
