### ISSUE TITLE
crash on hacking attempt via URL

### ISSUE THREAD

**Issue by gibsonf1** [fukamachi/woo#78]
A hacker was probing for vulnerability and with this url brought the system to a stop.  Is there a way to not go into debugger on strange url's?  I've been crashed several times this way.

185.100.87.246 - [16/Jan/2019:12:01:39 -09:00] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 302 38 "-" "-"

debugger invoked on a FAST-HTTP.ERROR:CB-MESSAGE-COMPLETE in thread
#<THREAD "clack-handler-woo" RUNNING {100980E2C3}>:
  Callback Error: the message-complete callback failed
(A SIMPLE-ERROR was caught when trying to print *DEBUG-CONDITION* when entering
the debugger. Printing was aborted and the SIMPLE-ERROR was stored in
SB-DEBUG::*NESTED-DEBUG-CONDITION*.)

**Comment by fukamachi** [comment]
Can't reproduce it. What version of fast-http are you using?
It might be fixed at https://github.com/fukamachi/fast-http/pull/37.
